# Generated by Django 3.1.3 on 2021-04-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empty',
            fields=[
                ('modelid', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
