# Generated by Django 3.1.3 on 2021-04-18 22:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AppCDV', '0003_auto_20210418_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelosclustering',
            name='algoritmo',
            field=models.CharField(default='K-means', max_length=50),
        ),
        migrations.AlterField(
            model_name='modelosclustering',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 22, 33, 25, 717567, tzinfo=utc)),
        ),
    ]
