# Generated by Django 3.1.3 on 2021-04-19 00:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AppCDV', '0004_auto_20210418_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelosclustering',
            name='id',
        ),
        migrations.AlterField(
            model_name='modelosclustering',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 0, 6, 20, 25080, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='modelosclustering',
            name='id_modelo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
