# Generated by Django 3.1.3 on 2021-04-20 02:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AppCDV', '0006_auto_20210420_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelosclustering',
            name='usuario',
        ),
        migrations.AddField(
            model_name='modelosclustering',
            name='autor',
            field=models.CharField(default='autor', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelosclustering',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 2, 57, 42, 568352, tzinfo=utc)),
        ),
    ]
