# Generated by Django 3.1.3 on 2021-04-28 00:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AppCDV', '0007_auto_20210420_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelosclustering',
            name='caracteristicas',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='modelosclustering',
            name='nombre_archivo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelosclustering',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 0, 6, 35, 910788, tzinfo=utc)),
        ),
    ]
