# Generated by Django 3.1.3 on 2021-04-28 00:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AppCDV', '0008_auto_20210428_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelosclustering',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 0, 16, 4, 750566, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='modelosclustering',
            name='id_modelo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
