# Generated by Django 3.1.3 on 2021-04-28 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AppCDV', '0009_auto_20210428_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelosclustering',
            name='estado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='modelosclustering',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 16, 52, 22, 451300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='modelosclustering',
            name='nombre_archivo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
