# Generated by Django 3.1.3 on 2021-04-29 00:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AppCDV', '0010_auto_20210428_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelosclustering',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modelosclustering',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 0, 20, 4, 775148, tzinfo=utc)),
        ),
    ]
